// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV45rKp90MVsRbI5SbNUWckZWDlEbshrA',
    appId: '1:769273831183:web:b268ef301427ff5d36687a',
    messagingSenderId: '769273831183',
    projectId: 'connections-test-b10de',
    authDomain: 'connections-test-b10de.firebaseapp.com',
    storageBucket: 'connections-test-b10de.appspot.com',
    measurementId: 'G-9FJRBS33PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnrlqLHGqwaVaMwrNSgdqKaYO-HBwezk0',
    appId: '1:769273831183:android:7b7d9986ecdf0cd936687a',
    messagingSenderId: '769273831183',
    projectId: 'connections-test-b10de',
    storageBucket: 'connections-test-b10de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA99R7cIqpXZYVVQQ2NWVT5Rvm0t4yhCig',
    appId: '1:769273831183:ios:6b3554132d63756136687a',
    messagingSenderId: '769273831183',
    projectId: 'connections-test-b10de',
    storageBucket: 'connections-test-b10de.appspot.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA99R7cIqpXZYVVQQ2NWVT5Rvm0t4yhCig',
    appId: '1:769273831183:ios:ba3e7db0c641de6d36687a',
    messagingSenderId: '769273831183',
    projectId: 'connections-test-b10de',
    storageBucket: 'connections-test-b10de.appspot.com',
    iosBundleId: 'com.example.chatty.RunnerTests',
  );
}
